GREETING: Hello From Sibutest!
SECRET_KEY: 'the-secret-is-here'
OAUTH_MWURI: https://commons.wikimedia.org/w/index.php
CONSUMER_KEY: b5717c97d99cb674e3ba6fc5469ae6fe
CONSUMER_SECRET: 0d927af8bb16c48b33cd9395e6cf484afd0ef153
